django_bitacora_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
    url(r'^$', views.Consultar.as_view(), name='consultar'),
    url(r'^registrar$', views.Registrar.as_view(), name='registrar'),
    url(r'^editar/(?P<pk>\d+)$', views.Editar.as_view(), name='editar'),
    url(r'^borrar/(?P<pk>\d+)$', views.Borrar.as_view(), name='borrar'),
    url(r'^bitacora', views.BitacoraView.as_view(), name='bitacora'),
)

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Persona(models.Model):
    nombre = models.CharField(max_length=200)
    cedula = models.CharField(max_length=8)

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('registro:editar', kwargs={'pk': self.pk})


class Bitacora(models.Model):
    entrada = models.CharField(max_length=200)

    def __unicode__(self):
        return self.entrada

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from datetime import datetime
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from django.contrib.auth.models import User
from registro.models import Persona, Bitacora


class Consultar(ListView):
    """
    Clase que muestra la lista de personas registradas
    """
    model = Persona

    def get(self, request, *args, **kwargs):
        """
        Método que muestra cual usuario y cuando visito la lista de personas.
        """
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
                          % {'class_name': self.__class__.__name__})
        context = self.get_context_data(object_list=self.object_list)
        #print "***** El usuario: "+str(self.request.user)+", visito la lista de personas el: "+str(datetime.now())+" *****"
        #a = "El usuario: "+str(self.request.user)+", visito la lista de personas el: "+str(datetime.now())
        #Bitacora.objects.create(entrada=a)
        return self.render_to_response(context)


class Registrar(CreateView):
    """
    Clase que permite registrar personas
    """
    model = Persona
    fields = ['nombre', 'cedula']
    success_url = reverse_lazy('registro:consultar')

    def form_valid(self, form):
        """
        Método que muestra cual usuario y cuando registro a una persona y lo guara en la tabla bitacora
        """
        self.object = form.save()
        #print "***** El usuario: "+str(self.request.user)+", registro una persona el: "+str(datetime.now())+" *****"
        a = "El usuario: "+str(self.request.user)+", registro una persona el: "+str(datetime.now())
        Bitacora.objects.create(entrada=a)
        return super(Registrar, self).form_valid(form)


class Editar(UpdateView):
    """
    Clase que permite editar a las personas
    """
    model = Persona
    fields = ['nombre', 'cedula']
    success_url = reverse_lazy('registro:consultar')

    def form_valid(self, form):
        """
        Método que muestra cual usuario y cuando actualizo a una persona y lo guara en la tabla bitacora
        """
        self.object = form.save()
        #print "***** El usuario: "+str(self.request.user)+", actualizo una persona el: "+str(datetime.now())+" *****"
        a = "El usuario: "+str(self.request.user)+", actualizó una persona el: "+str(datetime.now())
        Bitacora.objects.create(entrada=a)
        return super(Editar, self).form_valid(form)


class Borrar(DeleteView):
    """
    Clase que permite eliminar una persona
    """
    model = Persona
    success_url = reverse_lazy('registro:consultar')

    def delete(self, request, *args, **kwargs):
        """
        Método que muestra cual usuario y cuando elimino a una persona y lo guara en la tabla bitacora
        """
        #print "***** El usuario: "+str(self.request.user)+", elimino a una persona el: "+str(datetime.now())+" *****"
        a = "El usuario: "+str(self.request.user)+", elimino una persona el: "+str(datetime.now())
        Bitacora.objects.create(entrada=a)
        return super(Borrar, self).delete(self, request, *args, **kwargs)


class BitacoraView(ListView):
    """
    Clase que muestra la lista de entradas de la bitácora
    """
    model = Bitacora
    template_name = "registro/bitacora.html"

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>
    
    <!-- Fixed navbar
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'registro:consultar' %}">Bitácora de eventos del usuario</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:consultar' %}">Lista</a></li>
            <li><a href="{% url 'registro:registrar' %}">Registrar</a></li>
            <li><a href="{% url 'registro:bitacora' %}">Bitácora</a></li>
          </ul>
        </div>
      </div>
    </nav><!-- End navbar -->

    <br />
    <br />
    <br />

    <div class="container theme-showcase" role="main">
      <div class="well">
        {% block cuerpo %}
        {% endblock %}
      </div>
    </div> <!-- /container -->

  </body>
</html>

registro/templates/registro/bitacora.html
{% extends "registro/base.html" %}
{% block titulo %}Bitacora{% endblock %}
{% block cuerpo %}
<h1>Bitácora</h1>
<ul>
  {% for x in object_list %}
  <li>{{ x.id }} {{ x.entrada }}
  </li>
  {% endfor %}
</ul>
{% endblock %}

registro/templates/registro/persona_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  Are you sure you want to delete "{{ object }}" ?
  <input type="submit" value="Submit" />
</form>
{% endblock %}

registro/templates/registro/persona_form.html
{% extends "registro/base.html" %}
{% block titulo %}Registrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

registro/templates/registro/persona_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista{% endblock %}
{% block cuerpo %}
<h1>Personas</h1>
<ul>
  {% for persona in object_list %}
  <li>{{ persona.nombre }} {{ persona.cedula }}
  <a href="{% url 'registro:editar' persona.id %}">editar</a>
  <a href="{% url 'registro:borrar' persona.id %}">borrar</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}